DeebotUniverse/client.py

.pre-commit-config.yaml
deebot_client/commands/__init__.py
deebot_client/commands/common.py
deebot_client/commands/fan_speed.py
deebot_client/commands/volume.py
deebot_client/commands/water_info.py
deebot_client/events/__init__.py
deebot_client/events/const.py

Requested in https://github.com/And3rsL/Deebot-for-Home-Assistant/issues/121
Docs PR: https://github.com/DeebotUniverse/docs/pull/32

add volume

---

README.md
deebot_client/authentication.py

Fixes [lgtm alert](https://lgtm.com/projects/g/DeebotUniverse/client.py/snapshot/4dda3cce8e3c56cbd9891eea490c19fbae759a10/files/deebot_client/authentication.py?sort=name&dir=ASC&mode=heatmap#xd4a0a55ecb8156ad:1)

fix lgtm alert

---

deebot_client/map.py
pytest.ini
requirements-test.txt
tests/test_map.py

Fixes map error in https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/109

fix image_box is None

---

deebot_client/commands/clean_logs.py
deebot_client/commands/common.py
deebot_client/commands/map.py
pylintrc
requirements-test.txt
tests/commands/__init__.py
tests/commands/test_clean_log.py

https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/199

skip clean log entries if data is not correct

---

deebot_client/api_client.py

Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/196

fix error is optional

---

deebot_client/commands/map.py
tests/commands/test_map.py

Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/205

fix map commands handling

---

deebot_client/commands/clean_logs.py
deebot_client/events/__init__.py
deebot_client/messages/stats.py
tests/commands/test_clean_log.py
tests/messages/test_stats.py

Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/225
Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/210

CleanJobStatus can be missing

---

deebot_client/commands/water_info.py
deebot_client/events/water_info.py
tests/commands/test_water_info.py

Library fix for https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/302

allow mop_attached to be None

---

deebot_client/commands/map.py
deebot_client/events/const.py
deebot_client/events/map.py
tests/commands/test_map.py

Requested in https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/310

add CachedMapInfoEvent

---

requirements.txt

Relates to https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/374

pin asyncio-mqtt to 0.16.1

---

deebot_client/mqtt_client.py
requirements.txt
tests/conftest.py
tests/fixtures/base.py
tests/fixtures/mqtt_server.py
tests/test_mqtt_client.py

Needs https://github.com/sbtinstruments/aiomqtt/pull/232
Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/380

update and rename asyncio-mqtt to aiomqtt

---

deebot_client/map.py

Fixes https://github.com/DeebotUniverse/client.py/issues/279

map: fix divide-by-zero in dashed_line renderer

---

deebot_client/map.py
requirements-test.txt
tests/conftest.py
tests/test_map.py

Fixes https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/404

Fix rooms without enabled map

---

deebot_client/capabilities.py
deebot_client/command.py
deebot_client/commands/json/battery.py
deebot_client/commands/json/charge_state.py
deebot_client/commands/json/clean.py
deebot_client/commands/json/clean_count.py
deebot_client/commands/json/common.py
deebot_client/commands/json/error.py
deebot_client/commands/json/fan_speed.py
deebot_client/commands/json/life_span.py
deebot_client/commands/json/map.py
deebot_client/commands/json/network.py
deebot_client/commands/json/pos.py
deebot_client/commands/json/stats.py
deebot_client/commands/json/volume.py
deebot_client/commands/json/water_info.py
deebot_client/commands/json/work_mode.py
tests/commands/json/__init__.py
tests/commands/json/test_common.py

The motivation is that XML-based commands will need them too. See #288

Move CommandWithMessageHandling and SetCommand to command.py

---

deebot_client/capabilities.py
deebot_client/commands/json/error.py
deebot_client/hardware/deebot/p95mgv.py
tests/hardware/test_init.py

> See more general info and details under **[discussion](https://github.com/DeebotUniverse/client.py/discussions/345)**.

Add capabilities for Deebot T10 Plus (p95mgv)

---

deebot_client/events/__init__.py
deebot_client/hardware/deebot/x5d34r.py
tests/commands/json/test_life_span.py

ROUND_MOP = "Mopping pad" (e.g. X1 series)
AIR_FRESHENER = "Air Freshener" (e.g. T9 series, Airbot Z1)
UV_SANITIZER = "UV Sanitizer Module" (Airbot Z1)
HUMIDIFY = "Humidification Filter" (Airbot Z1)
HUMIDIFY_MAINTENANCE = "Humidification Module Maintenance" (Airbot Z1)

Add several LifeSpan components

---

deebot_client/api_client.py
deebot_client/authentication.py
deebot_client/const.py
deebot_client/models.py
tests/commands/__init__.py
tests/conftest.py

Required to get old devices.
Ref: https://github.com/home-assistant/core/issues/110007

Get devices from GetDeviceList too

---

deebot_client/messages/__init__.py

New commands should implement also a Message if a event is expected

Allow legacy fallback only for current commands

---

README.md
deebot_client/authentication.py
deebot_client/capabilities.py
deebot_client/event_bus.py
deebot_client/events/efficiency_mode.py
deebot_client/hardware/deebot/2o4lnm.py
deebot_client/hardware/deebot/fallback.py
deebot_client/hardware/deebot/p1jij8.py
deebot_client/hardware/deebot/p95mgv.py
deebot_client/hardware/deebot/x5d34r.py
deebot_client/hardware/deebot/yna5xi.py
deebot_client/map.py
deebot_client/models.py
deebot_client/mqtt_client.py
deebot_client/util/__init__.py
deebot_client/util/continents.py
tests/commands/json/test_common.py
tests/commands/json/test_efficiency.py
tests/helpers/tasks.py
tests/messages/json/test_map.py
tests/test_authentication.py
tests/test_device.py
tests/test_event_bus.py
tests/test_mqtt_client.py
tests/util/test_continents.py

Nitpicks text

---

README.md

This makes some changes to make the code example in Readme work.

Readme: adjust example to make it work

---

deebot_client/commands/xml/__init__.py
deebot_client/commands/xml/pos.py
tests/commands/xml/test_pos.py

This adds new GetPos command for xml vacuums like ls1ok3.
Example: [GetPos.txt](https://github.com/DeebotUniverse/client.py/files/14705746/GetPos.txt)

Add xml command "GetPos"

---

deebot_client/commands/json/map.py
deebot_client/map.py
deebot_client/message.py
tests/commands/__init__.py
tests/commands/json/test_map.py
tests/test_map.py

Relates to https://github.com/home-assistant/core/issues/116922

Fix map subset parsing on newer bots

---

deebot_client/commands/json/pos.py
deebot_client/commands/xml/pos.py
deebot_client/events/map.py
tests/commands/json/test_pos.py
tests/commands/xml/test_pos.py
tests/test_map.py

Add "angle" in Position

---

deebot_client/hardware/deebot/m1wkuw.py

Add support for Deebot N10

---

deebot_client/hardware/deebot/4bdkrs.py

Resolves https://github.com/DeebotUniverse/client.py/issues/683

Add T30S Combo support
